# Generated by Django 5.2.16 on 2026-08-05 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreditDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('invoice_number', models.CharField(max_length=100)),
                ('note_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditDebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.creditdebitnote')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_to_projects', to='notes.company')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_projects', to='notes.company')),
            ],
        ),
        migrations.AddField(
            model_name='creditdebitnote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.project'),
        ),
    ]
